const filtersData = {
	Order: ['popular', 'latest', 'upcoming', "editor's choice"],
	Type: ['all', 'photo', 'illustration', 'vector'],
	Orientation: ['all', 'horizontal', 'vertical'],
	Size: [],
	Category: [
		'all',
		'backgrounds',
		'fashion',
		'nature',
		'science',
		'education',
		'feelings',
		'health',
		'people',
		'religion',
		'places',
		'animals',
		'industry',
		'computer',
		'food',
		'sports',
		'transportation',
		'travel',
		'buildings',
		'business',
		'music',
	],
	Color: [
		'grayscale',
		'transparent',
		'red',
		'orange',
		'yellow',
		'green',
		'turquoise',
		'blue',
		'lilac',
		'pink',
		'white',
		'gray',
		'black',
		'brown',
	],
};

export default filtersData;
